### ISSUE TITLE
CSS.supports is not a function on eruda 3.x

### ISSUE THREAD

**Issue by usizu** [liriliri/eruda#530]
Immediately after initialisation I get this error:

```
Uncaught TypeError: CSS.supports is not a function
    it util.js:16
    it DevTools.js:263
    it DevTools.js:63
    n ready.js:14
    5570 ready.js:8
    Webpack 9
```

Using vite with default eruda setup:

`"eruda": "^3.4.3"`

or

`<script src="https://cdn.jsdelivr.net/npm/eruda"></script>`

It works fine with eruda 2.11.0 but fails with anything higher

Tried it on desktop with both Firefox and Safari as well as Safari on iOS.

Happy to provide any other info or test something out
